### ISSUE TITLE
remove update folder 

### ISSUE THREAD

**Issue by janstuemmel** [crinis/hlxce-docker#1]
on installation i says, i should remove the update folder...

![download](https://user-images.githubusercontent.com/7893682/30641915-084bb552-9e09-11e7-959c-44c2c52cafdf.png)

**Comment by janstuemmel** [comment]
ahh ok my bad, you explained this in README. but it doesn't work for my. what do you mean by removing the service and restart?

**Comment by crinis** [comment]
When the environment variable UPDATE_DB is not set or set to something else than true, it will automatically remove your updater folder during container start. This means you have to restart or recreate the container after changing the environment variable.
